# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Sehr wichtig', 'Sehr wichtig'), ('Wichtig', 'Wichtig'), ('Ein bisschen wichtig', 'Ein bisschen wichtig'), ('Nicht wichtig', 'Nicht wichtig')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_answer_importance',
            field=models.CharField(choices=[('Sehr wichtig', 'Sehr wichtig'), ('Wichtig', 'Wichtig'), ('Ein bisschen wichtig', 'Ein bisschen wichtig'), ('Nicht wichtig', 'Nicht wichtig')], max_length=50),
        ),
    ]
