# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landingpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='')),
                ('symbol', models.ImageField(upload_to='')),
                ('claim', models.CharField(max_length=250)),
                ('tagline', models.TextField(max_length=500)),
                ('cta', models.CharField(max_length=250)),
            ],
        ),
    ]
