# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 13:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import landingpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='bg_img',
            field=models.ImageField(upload_to=landingpage.models.upload_location),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='cta',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='symbol',
            field=models.ImageField(upload_to=landingpage.models.upload_location),
        ),
    ]
