# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20160411_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/screenshots/', verbose_name='Screenshot'),
        ),
    ]
