# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20161029_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=feedback.models.upload_location, verbose_name='Screenshot'),
        ),
    ]
