# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import ideas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=ideas.models.upload_location)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Titel')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Beschreibung')),
                ('author', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email des Autors')),
                ('subm_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Datum')),
                ('active', models.BooleanField(default=False, verbose_name='veröffentlicht?')),
            ],
            options={
                'verbose_name': 'Idee',
                'verbose_name_plural': 'Ideen',
            },
        ),
    ]
