# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import ideas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=ideas.models.upload_location, verbose_name='Bild'),
        ),
    ]
