# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0002_auto_20161007_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.ManyToManyField(related_name='likes_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
