# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20161025_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured?'),
        ),
        migrations.AddField(
            model_name='idea',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
