# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20161102_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='link',
        ),
    ]
