# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideas.Idea'),
        ),
    ]
