# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-03 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_auto_20161107_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Privat'),
        ),
    ]
