# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-03 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20161203_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Privat: '),
        ),
    ]
