# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_auto_20161203_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='private',
            field=models.BooleanField(verbose_name='Privat: '),
        ),
    ]
