# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_auto_20161203_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Freigegeben'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Privat '),
        ),
    ]
