# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_auto_20161205_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='active',
            new_name='enabled',
        ),
    ]
