# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_auto_20170105_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ohne Projekt'),
        ),
    ]
