# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models

def set_active(apps, schema_editor):
    Idea = apps.get_model("ideas", "Idea")
    Project = apps.get_model("socialee", "Project")
    for idea in Idea.objects.all():
        if Project.objects.filter(title=idea.title).exists():
            idea.active = False 
            idea.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_idea_active'),
        ('socialee', '0042_message'),
    ]

    operations = [
        migrations.RunPython(set_active),
    ]
