# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0048_auto_20170202_1508'),
        ('ideas', '0017_auto_20170105_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Project'),
        ),
    ]
