# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:16
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25)),
                ('title', models.CharField(max_length=200, verbose_name="What's the offer?")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25)),
                ('title', models.CharField(max_length=200, verbose_name="What's the request?")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('plz', models.CharField(blank=True, default='10969', max_length=5, null=True)),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=5000)),
                ('inputs', models.ManyToManyField(to='socialee.Input')),
                ('liked_users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Profile')),
                ('outputs', models.ManyToManyField(to='socialee.Output')),
                ('profiles', models.ManyToManyField(to='socialee.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Zettel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='zettel/%Y-%m/')),
                ('number', models.CharField(blank=True, default='2015_000_0000', max_length=50, null=True, verbose_name='Number on the zettel')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Origin')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile')),
            ],
            options={
                'verbose_name_plural': 'Zettel',
            },
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'abstract': False,
                'verbose_name_plural': 'User-Erfassungen',
                'verbose_name': 'User-Erfassung',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Origin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.UserEntry'),
        ),
        migrations.AddField(
            model_name='output',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='output',
            name='zettel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Zettel'),
        ),
        migrations.AddField(
            model_name='input',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='input',
            name='zettel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Zettel'),
        ),
    ]
