# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import socialee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'sonstige'), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25)),
                ('title', models.CharField(max_length=200, verbose_name='Was ist der Input?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Nachricht')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False, verbose_name='erledigt?')),
            ],
            options={
                'verbose_name': 'Bitte ladet mich ein!',
                'verbose_name_plural': 'Bitte ladet mich ein!',
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'sonstige'), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25)),
                ('title', models.CharField(max_length=200, verbose_name='Was ist der Output?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('plz', models.CharField(blank=True, max_length=5, null=True)),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('tagline', models.CharField(max_length=140, null=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Zettel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='zettel/%Y-%m/')),
                ('number', models.CharField(blank=True, default='2015_000_0000', max_length=50, null=True, verbose_name='Number on the zettel')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Origin')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile')),
            ],
            options={
                'verbose_name_plural': 'Zettel',
            },
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'manuelle User Erfassung',
                'abstract': False,
                'verbose_name_plural': 'manuelle User Erfassungen',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='inputs',
            field=models.ManyToManyField(to='socialee.Input'),
        ),
        migrations.AddField(
            model_name='project',
            name='liked_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='Project_Managers', to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='outputs',
            field=models.ManyToManyField(to='socialee.Output'),
        ),
        migrations.AddField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(related_name='Socialeebhaber', to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Origin'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='output',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='output',
            name='zettel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Zettel'),
        ),
        migrations.AddField(
            model_name='input',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='input',
            name='zettel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Zettel'),
        ),
    ]
