# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
