# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userentry',
            options={'verbose_name': 'manuelle User Erfassung', 'verbose_name_plural': 'manuelle User Erfassungen'},
        ),
        migrations.AlterField(
            model_name='input',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Was ist der Input?'),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(choices=[('', 'sonstige'), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='output',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Was ist der Output?'),
        ),
        migrations.AlterField(
            model_name='output',
            name='type',
            field=models.CharField(choices=[('', 'sonstige'), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plz',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
