# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0002_remove_project_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='Project_Managers', to='socialee.Profile'),
        ),
    ]
