# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0002_delete_invite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEntry',
        ),
    ]
