# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0002_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 5, 31, 22, 4, 55, 950711, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
