# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0002_auto_20160429_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
