# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0003_delete_userentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='origin',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
