# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0003_project_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='Project_Managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='profiles',
            field=models.ManyToManyField(related_name='Socialeebhaber', to=settings.AUTH_USER_MODEL),
        ),
    ]
