# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0004_auto_20160710_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='liked_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
