# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0004_auto_20160824_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
