# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0004_auto_20160429_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
