# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0005_auto_20160710_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outputs',
        ),
    ]
