# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0006_remove_profile_liked_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ManyToManyField(related_name='likes', to='socialee.Project'),
        ),
    ]
