# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import socialee.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0006_auto_20160710_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location),
        ),
    ]
