# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0006_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='message',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Nachricht'),
        ),
    ]
