# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0007_auto_20160521_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='done',
            field=models.BooleanField(default=False, verbose_name='erledigt?'),
        ),
    ]
