# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0007_profile_liked_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonGround',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='profile',
            name='commonground_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialee.CommonGround'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='commonground_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialee.CommonGround'),
            preserve_default=False,
        ),
    ]
