# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0009_auto_20160710_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zettel',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='zettel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='input',
            name='zettel',
        ),
        migrations.RemoveField(
            model_name='output',
            name='zettel',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='Project_Managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Zettel',
        ),
    ]
