# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialee', '0010_auto_20160922_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='commonground',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='commonground',
            name='profiles',
            field=models.ManyToManyField(related_name='socialeebhaber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonground',
            name='projects',
            field=models.ManyToManyField(related_name='likes', to='socialee.Project'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='tagline',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='commonground',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
