# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0010_auto_20160710_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'sonstige'), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25)),
                ('title', models.CharField(max_length=200, verbose_name='Tag-Beschreibung')),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='input',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='inputs',
            field=models.ManyToManyField(to='socialee.Input'),
        ),
        migrations.AddField(
            model_name='project',
            name='outputs',
            field=models.ManyToManyField(to='socialee.Output'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='socialee.Tag'),
        ),
    ]
