# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0011_auto_20160710_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='inputs',
            field=models.ManyToManyField(blank=True, to='socialee.Input'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outputs',
            field=models.ManyToManyField(blank=True, to='socialee.Output'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='socialee.Tag'),
        ),
    ]
