# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialee.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialee', '0013_remove_project_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('plz', models.CharField(blank=True, max_length=5, null=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_messages',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_profiles',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_projects',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='outputs',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='commonground_ptr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='commonground_ptr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='input',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='output',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CommonGround',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
