# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
        ('socialee', '0013_remove_project_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSlugTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.SlugField(verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialee_genericslugtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialee_genericslugtaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='commonground',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='socialee.GenericSlugTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
