# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialee.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialee', '0014_auto_20160924_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonGround',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('tagline', models.CharField(max_length=140, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile_fake',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project_fake',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('commonground_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialee.CommonGround')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('plz', models.CharField(blank=True, max_length=5, null=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('socialee.commonground',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('commonground_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialee.CommonGround')),
                ('title', models.CharField(max_length=60)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(blank=True, related_name='Project_Managers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('socialee.commonground',),
        ),
        migrations.DeleteModel(
            name='Profile_fake',
        ),
        migrations.DeleteModel(
            name='Project_fake',
        ),
        migrations.AddField(
            model_name='commonground',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.Conversation'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='inputs',
            field=models.ManyToManyField(blank=True, to='socialee.Input'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='liked_messages',
            field=models.ManyToManyField(related_name='message_likes', to='socialee.Message'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='liked_profiles',
            field=models.ManyToManyField(related_name='profile_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonground',
            name='outputs',
            field=models.ManyToManyField(blank=True, to='socialee.Output'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='input',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.CommonGround'),
        ),
        migrations.AddField(
            model_name='output',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialee.CommonGround'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='liked_projects',
            field=models.ManyToManyField(related_name='project_likes', to='socialee.Project'),
        ),
    ]
