# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0015_auto_20160924_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonground',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
