# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import socialee.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0017_auto_20160924_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='history',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longdescription',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=socialee.models.upload_location),
        ),
    ]
