# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0017_auto_20150824_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dream',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='profiles',
        ),
        migrations.AddField(
            model_name='input',
            name='type',
            field=models.CharField(choices=[('', ''), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='output',
            name='type',
            field=models.CharField(choices=[('', ''), ('knowledge', 'Wissen'), ('skill', 'Fähigkeit'), ('problem', 'Problem'), ('resource', 'Resource'), ('solution', 'Lösung')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='liked_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='socialee.Profile'),
        ),
        migrations.DeleteModel(
            name='Dream',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
