# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0022_auto_20161004_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonground',
            name='inputs',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='outputs',
        ),
        migrations.AlterField(
            model_name='input',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialee_input', to='socialee.CommonGround'),
        ),
        migrations.AlterField(
            model_name='output',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialee_output', to='socialee.CommonGround'),
        ),
    ]
