# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0024_auto_20161006_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='by_user',
            new_name='by_instance',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_profiles',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_projects',
        ),
        migrations.AddField(
            model_name='commonground',
            name='follows_profiles',
            field=models.ManyToManyField(related_name='profile_follower', to='socialee.Profile'),
        ),
        migrations.AddField(
            model_name='commonground',
            name='follows_projects',
            field=models.ManyToManyField(related_name='project_follower', to='socialee.Project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
