# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0025_auto_20161008_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='user',
        ),
    ]
