# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 15:29
from __future__ import unicode_literals

from django.db import migrations

def move_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Profile = apps.get_model("socialee", "Profile")
    Project = apps.get_model("socialee", "Project")
    for profile in Profile.objects.all():
        profile.created_by = profile.user
        profile.save()
    for project in Project.objects.all():
        project.created_by = project.user
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0027_commonground_created_by'),
    ]

    operations = [
        migrations.RunPython(move_user),
    ]
