# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0030_auto_20161008_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonground',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
