# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0031_commonground_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
