# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0032_auto_20161012_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonground',
            name='follows_profiles',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='follows_projects',
        ),
        migrations.AddField(
            model_name='commonground',
            name='follows',
            field=models.ManyToManyField(related_name='follower', to='socialee.CommonGround'),
        ),
    ]
