# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0033_auto_20161027_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
    ]
