# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-12 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialee.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialee', '0038_auto_20161211_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=socialee.models.upload_location_user_pic)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='liked_messages',
        ),
        migrations.AddField(
            model_name='commonground',
            name='follower',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commonground',
            name='inst_follower',
            field=models.ManyToManyField(related_name='inst_follows', to='socialee.CommonGround'),
        ),
    ]
