# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0039_auto_20161212_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
