# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0040_auto_20161227_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='by_instance',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
