# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-27 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0041_message_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='by_instance',
        ),
        migrations.RemoveField(
            model_name='message',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
