# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0042_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtaggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='locationtaggeditem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='location',
        ),
        migrations.DeleteModel(
            name='LocationTag',
        ),
        migrations.DeleteModel(
            name='LocationTaggedItem',
        ),
    ]
