# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('socialee', '0043_auto_20170105_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialee.CommonGround')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialee_locationtaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commonground',
            name='location',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='socialee.LocationTaggedItem', to='taggit.Tag', verbose_name='Location'),
        ),
    ]
