# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0045_auto_20170112_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonground',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='commonground',
            name='inst_follower',
        ),
    ]
