# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialee', '0047_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='likes_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
