# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialee', '0048_auto_20170202_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='dateJoined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Details erstellt am:'),
        ),
    ]
