# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Zitat')),
                ('author', models.CharField(max_length=120, verbose_name='Autor')),
                ('subm_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Datum')),
                ('active', models.BooleanField(default=False, verbose_name='veröffentlicht?')),
            ],
            options={
                'verbose_name_plural': 'Zitate',
                'verbose_name': 'Zitat',
            },
        ),
    ]
