# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='autor',
            new_name='author',
        ),
    ]
