# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20160429_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
