# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Zitat', 'verbose_name_plural': 'Zitate'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=False, verbose_name='veröffentlicht?'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.TextField(max_length=250, verbose_name='Zitat'),
        ),
    ]
