# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20160508_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='subm_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='eingereicht'),
        ),
    ]
