# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_subm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='subm_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum'),
        ),
    ]
